apiVersion: apps/v1
kind: Deployment
metadata:
  name: corebanking
  namespace: embedded-finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: corebanking
  template:
    metadata:
      labels:
        app: corebanking
    spec:
      containers:
      - name: corebanking
        image: embedded-finance-api:latest
        command: ["dotnet", "CoreBanking/CoreBanking.dll"]
        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:5001"
        - name: ConnectionStrings__Postgres
          value: "Host=postgres;Database=banking;Username=postgres;Password=yourpassword"
        - name: ConnectionStrings__Redis
          value: "redis:6379"
        - name: ConnectionStrings__RabbitMQ
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: Jwt__Issuer
          value: "EmbeddedFinanceAPI"
        - name: Jwt__Audience
          value: "EmbeddedFinanceClients"
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: corebanking
  namespace: embedded-finance
spec:
  selector:
    app: corebanking
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: embedded-finance
type: Opaque
data:
  key: U3VwZXJTZWNyZXRLZXlGb3JKd3dUb2tlbkdlbmVyYXRpb24=  # base64 encoded JWT key 